### PR TITLE
Fontawesome Migration

### PR DESCRIPTION
**Pull request by XileHorizon**
We were using Fontawesome hosted by Fontawesome but we surpassed the free amount of site views so I added the files to our assets folder to continue using their icons

### CODE REVIEW

**Review by tooshel — APPROVED** [review]
looks good now with the relative paths but it does suck we have to include all this in the repo instead of usin a vpn

**Review by stavares843 — CHANGES_REQUESTED** [review]
as I mentioned to Sheldon, we don't need to use a font-awesome kit in order to update the X logo since they have that icon free on their library as long we use the 6.4.2 version or older

here's a PR addressing that change
https://github.com/Satellite-im/uplink.satellite.im/pull/24

image

**Comment by XileHorizon** [comment]
I significantly reduced the number of SVGs in the folder. We are using more than just the X logo, and I plan to use others as well. We need to get this change in soon before we have no icons at all when Fontawesome cuts us off, they have already sent me warnings.

**Comment by XileHorizon** [comment]
I think there is some confusion. I know they're free but to have fontawesome host the icons, they have usage limits if you don't want to pay a fee. They're free if we host them.

**Comment by XileHorizon** [comment]
I think there is some confusion. I know they're free but to have fontawesome host the icons, they have usage limits if you don't want to pay a fee. They're free if we host them.

**Comment by stavares843** [comment]
Yes I do know that but do we need to even host any icons at this point? Seems we only use discord/github/dark mode/twitter icons. What other icons would we use where we would have to host them? All of these are free thats what i meant 😄

**Comment by XileHorizon** [comment]
I kept only the icons we use/may use in the future and removed all others, but just do your thing if it means we won't lose all of our icons soon. The main thing I care about is that we're spending money to funnel people to this website so we need to move fast on things that could break and lower the quality of the site.

**Review by stavares843 — APPROVED** [review]

**Pull request merged**
